import joblib
import streamlit as st
import pandas as pd
import json

@st.cache_resource
def load_model():
    return joblib.load("House_price_model_2.pkl")

@st.cache_data
def load_lookup():
    return pd.read_csv("state_city_lookup.csv")

@st.cache_data
def load_metrics():
    with open("metrics.json") as f:
        return json.load(f)

model = load_model()
lookup = load_lookup()
metrics = load_metrics()

st.set_page_config(
    page_title="US House Price Prediction",
    page_icon="🏡",
    layout="wide"
)

st.title("🏡 US House Price Predictor")

st.markdown("""
### Predict house prices in seconds

Powered by Ridge Regression and trained on over **1 million** US homes.
""")

st.divider()

col1, col2, col3 = st.columns(3)

col1.metric(
    "R2 Score",
    f'{metrics["r2"]:.3f}'
)

col2.metric(
    "Test MAE",
    f'${metrics["test_mae"]:,.0f}'

)

col3.metric(
    "RMSE",
    f'${metrics["rmse"]:,.0f}'
)

st.divider()

st.sidebar.title("About the Model")

st.sidebar.markdown(
    f"""
                    
    ### Performance

    - **R²:** {metrics["r2"]:.3f}

    - **Test MAE:** ${metrics["test_mae"]:,.0f}

    - **RMSE:** ${metrics["rmse"]:,.0f}
    
    """
)

st.sidebar.info(
    """
    This application predicts US house prices using a machine learning model.

    **Model**
    - Ridge Regression

    **Features**
    - Bedrooms
    - Bathrooms
    - House Size
    - Lot Size
    - City
    - State
    """
)

st.subheader("House Information")

st.info(
"""
Provide the details of the property you want to value.

• Bedrooms – Number of bedrooms

• Bathrooms – Number of bathrooms

• House Size – Interior living area (square feet)

• Lot Size – Land area (square feet)

• State – US state where the property is located

• City – City where the property is located
"""
)

left, right = st.columns(2)

with left:
    bed = st.slider(
        "bedrooms",
        1, 
        10,
        3
    )
    
    bath = st.slider(
        "bathrooms",
        1,
        10,
        2
    )
    
    house_size = st.slider(
        "House Size (sqft)",
        500,
        10000,
        2000
    )
    

# lookup = pd.read_csv("state_city_lookup.csv")

states = sorted(lookup["state"].dropna().unique())

cities = lookup["city"].dropna().unique()

with right:
    sqft_lot = st.slider(
        "Lot size (sqft)",
        500,
        100000,
        10000
    )
    
    state = st.selectbox(
        "State",
        states
    )
    
    filtered_cities = (
    lookup[lookup["state"] == state]["city"]
    .dropna()
    .sort_values()
    .unique()
    )
    
    city = st.selectbox(
        "City",
        filtered_cities
    )

if st.button("Predict Price"):
    
    sqft_per_bed = house_size/bed
    
    new_house = pd.DataFrame({
        
        "bed": [bed],
        "bath": [bath],
        "house_size": [house_size],
        "sqft_lot": [sqft_lot],
        "sqft_per_bed": [sqft_per_bed],
        "city": [city],
        "state": [state]
        
       })
    
    prediction = model.predict(new_house)[0]
    
    st.metric(
       "Estimated House Price",
       f"${prediction:,.0f}"
    )
    
    st.subheader("Your input")
    
    st.dataframe(new_house)
    
    st.caption(
        "Predictions are generated by a machine learning model and should be treated as estimates rather than official property valuations."
    )

