import joblib
import streamlit as st
import pandas as pd

model=joblib.load("House_price_model.pkl")

st.set_page_config(
    page_title="US House Price Prediction",
    page_icon="🏡",
    layout="wide"
)

st.title("🏡 US House Price Predictor")

st.markdown("""
### Predict house prices in seconds

Powered by Ridge Regression and trained on over **1 million** US homes.
""")

st.divider()

col1, col2, col3 = st.columns(3)

col1.metric(
    "R2 Score",
    "0.727"
)

col2.metric(
    "Test MAE",
    "$93,639"
)

col3.metric(
    "RMSE",
    "$157,347"
)

st.divider()

st.sidebar.title("About the Model")

st.sidebar.info(
    """
    This application predicts US house prices using a machine learning model.

    **Model**
    - Ridge Regression

    **Features**
    - Bedrooms
    - Bathrooms
    - House Size
    - Lot Size
    - City
    - State

    **Performance**
    - R² = 0.727
    - MAE ≈ $93,600
    """
)

st.subheader("House Information")

st.info(
"""
Provide the details of the property you want to value.

• Bedrooms – Number of bedrooms

• Bathrooms – Number of bathrooms

• House Size – Interior living area (square feet)

• Lot Size – Land area (square feet)

• State – US state where the property is located

• City – City where the property is located
"""
)

left, right = st.columns(2)

with left:
    bed = st.slider(
        "bedrooms",
        1, 
        10,
        3
    )
    
    bath = st.slider(
        "bathrooms",
        1,
        10,
        2
    )
    
    house_size = st.slider(
        "House Size (sqft)",
        500,
        10000,
        2000
    )
    
df = pd.read_csv("realtor-data.zip.csv")

states = sorted(df["state"].dropna().unique())

cities = df["city"].dropna().unique()

with right:
    sqft_lot = st.slider(
        "Lot size (sqft)",
        500,
        100000,
        10000
    )
    
    state = st.selectbox(
        "State",
        states
    )
    
    filtered_cities = (
    df[df["state"] == state]["city"]
    .dropna()
    .sort_values()
    .unique()
    )
    
    city = st.selectbox(
        "City",
        filtered_cities
    )

if st.button("Predict Price"):
    
    sqft_per_bed = house_size/bed
    
    new_house = pd.DataFrame({
        
        "bed": [bed],
        "bath": [bath],
        "house_size": [house_size],
        "sqft_lot": [sqft_lot],
        "sqft_per_bed": [sqft_per_bed],
        "city": [city],
        "state": [state]
        
       })
    
    prediction = model.predict(new_house)[0]
    
    st.metric(
       "Estimated House Price",
       f"${prediction:,.0f}"
    )
    
    st.subheader("User input")
    
    st.dataframe(new_house)
    
    st.caption(
        "Predictions are generated by a machine learning model and should be treated as estimates rather than official property valuations."
    )

